# Generated by Django 3.0.2 on 2020-01-13 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='filled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='times',
            name='time_start',
            field=models.TimeField(choices=[(datetime.time(9, 0), datetime.time(9, 0)), (datetime.time(15, 0), datetime.time(15, 0)), (datetime.time(11, 0), datetime.time(11, 0))]),
        ),
    ]
